export const fileSystem = {
  id: "root",
  name: "/",
  type: "directory",
  children: [
    {
      id: "applications",
      name: "Applications",
      type: "directory",
      children: [
        {
          id: "finder",
          name: "Finder.app",
          type: "app",
          app: "finder",
          icon: "finder",
          technology: "React + Vite",
        },
        {
          id: "terminal",
          name: "Terminal.app",
          type: "app",
          app: "terminal",
          icon: "terminal",
          technology: "React + xterm.js",
        },
        {
          id: "settings",
          name: "Settings.app",
          type: "app",
          app: "settings",
          icon: "settings",
          technology: "React + Context",
        },
      ],
    },
    {
      id: "documents",
      name: "Documents",
      type: "directory",
      children: [
        {
          id: "resume",
          name: "Resume.pdf",
          type: "file",
          file: "resume",
          icon: "pdf",
          technology: "PDF",
        },
      ],
    },
    {
      id: "portfolio",
      name: "Portfolio",
      type: "directory",
      children: [
        {
          id: "about",
          name: "About",
          type: "page",
          page: "about",
          icon: "profile",
          technology: "React",
        },
        {
          id: "projects-page",
          name: "Projects",
          type: "page",
          page: "projects",
          icon: "folder",
          technology: "React + Framer Motion",
        },
        {
          id: "skills",
          name: "Skills",
          type: "page",
          page: "skills",
          icon: "code",
          technology: "JavaScript",
        },
        {
          id: "education",
          name: "Education",
          type: "page",
          page: "education",
          icon: "graduation",
          technology: "React",
        },
        {
          id: "achievements",
          name: "Achievements",
          type: "page",
          page: "achievements",
          icon: "trophy",
          technology: "React",
        },
        {
          id: "resume-page",
          name: "Resume",
          type: "page",
          page: "resume",
          icon: "pdf",
          technology: "PDF Viewer",
        },
        {
          id: "contact",
          name: "Contact",
          type: "page",
          page: "contact",
          icon: "mail",
          technology: "EmailJS",
        },
      ],
    },
    {
      id: "projects",
      name: "Workspace",
      type: "directory",
      technology: "Development",
      children: [
        {
          id: "kos",
          name: "K-OS",
          type: "directory",
          technology: "React + Vite",
          children: [
            { id: "kos-readme", name: "README.md", type: "file" },
            { id: "kos-package", name: "package.json", type: "file" },
            { id: "kos-src", name: "src", type: "directory", children: [] },
            {
              id: "kos-public",
              name: "public",
              type: "directory",
              children: [],
            },
            {
              id: "kos-assets",
              name: "assets",
              type: "directory",
              children: [],
            },
            {
              id: "kos-github",
              name: "GitHub.url",
              type: "link",
              url: "https://github.com/ksvxydv/keshavs-workspace",
            },
            {
              id: "kos-demo",
              name: "Live Demo.url",
              type: "link",
              url: "#",
            },
          ],
        },
        {
          id: "college",
          name: "College",
          type: "directory",
          technology: "Documents",
          children: [
            {
              id: "semester-1",
              name: "Semester 1",
              type: "directory",
              children: [],
            },
            {
              id: "semester-2",
              name: "Semester 2",
              type: "directory",
              children: [],
            },
            { id: "notes", name: "Notes", type: "directory", children: [] },
          ],
        },
        {
          id: "dsa",
          name: "DSA",
          type: "directory",
          technology: "C++17",
          children: [
            {
              id: "leetcode",
              name: "LeetCode",
              type: "directory",
              children: [],
            },
            {
              id: "codeforces",
              name: "Codeforces",
              type: "directory",
              children: [],
            },
            { id: "dsa-notes", name: "Notes.md", type: "file" },
          ],
        },
        {
          id: "ai-projects",
          name: "AI Projects",
          type: "directory",
          technology: "OpenAI",
          children: [
            {
              id: "ai-assistant",
              name: "AI Assistant",
              type: "directory",
              children: [{ id: "ai-readme", name: "README.md", type: "file" }],
            },
          ],
        },
      ],
    },
    {
      id: "downloads",
      name: "Downloads",
      type: "directory",
      technology: "Directory",
      children: [],
    },
  ],
};
