export const fileSystem = {
  id: "root",
  name: "/",
  type: "directory",
  children: [
    {
      id: "applications",
      name: "Applications",
      type: "directory",
      children: [
        {
          id: "finder",
          name: "Finder.app",
          type: "app",
          app: "finder",
          icon: "finder",
          technology: "React + Vite",
        },
        {
          id: "terminal",
          name: "Terminal.app",
          type: "app",
          app: "terminal",
          icon: "terminal",
          technology: "React + xterm.js",
        },
        {
          id: "settings",
          name: "Settings.app",
          type: "app",
          app: "settings",
          icon: "settings",
          technology: "React + Context",
        },
      ],
    },
    {
      id: "documents",
      name: "Documents",
      type: "directory",
      children: [
        {
          id: "resume",
          name: "Resume.pdf",
          type: "file",
          file: "resume",
          icon: "pdf",
          technology: "PDF",
        },
      ],
    },
    {
      id: "portfolio",
      name: "Portfolio",
      type: "directory",
      children: [
        {
          id: "about",
          name: "About",
          type: "page",
          page: "about",
          icon: "profile",
          technology: "React",
        },
        {
          id: "projects-page",
          name: "Projects",
          type: "page",
          page: "projects",
          icon: "folder",
          technology: "React + Framer Motion",
        },
        {
          id: "skills",
          name: "Skills",
          type: "page",
          page: "skills",
          icon: "code",
          technology: "JavaScript",
        },
        {
          id: "education",
          name: "Education",
          type: "page",
          page: "education",
          icon: "graduation",
          technology: "React",
        },
        {
          id: "achievements",
          name: "Achievements",
          type: "page",
          page: "achievements",
          icon: "trophy",
          technology: "React",
        },
        {
          id: "resume-page",
          name: "Resume",
          type: "page",
          page: "resume",
          icon: "pdf",
          technology: "PDF Viewer",
        },
        {
          id: "contact",
          name: "Contact",
          type: "page",
          page: "contact",
          icon: "mail",
          technology: "EmailJS",
        },
      ],
    },
    {
      id: "downloads",
      name: "Downloads",
      type: "directory",
      technology: "Directory",
      children: [],
    },
  ],
};
